---
- name: Provision infrastructure on AWS
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Launch web server instances
      ec2:
        count: 1
        instance_type: t2.micro
        image: ami-05295b6e6c790593e  # Example AMI ID for Amazon Linux
        key_name: sagar
        region: ap-south-1
        group: Ansible-SG
        instance_tags:
          Name: WebServer
        wait: yes
      register: web_servers

    - name: Launch application server instances
      ec2:
        count: 1
        instance_type: t2.micro
        image: ami-05295b6e6c790593e  # Example AMI ID for Amazon Linux
        key_name: sagar
        region: ap-south-1
        group: Ansible-SG
        instance_tags:
          Name: AppServer
        wait: yes
      register: app_servers

