---
- name: Install and configure Nginx
  hosts: ec2
  become: true
  vars_files:
    - nginx_vars.yml
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: latest

    - name: Configure Nginx document root
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Reload Nginx
    
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded


