---
- name: Configuring backend servers for load balancer
  hosts: ec2
  become: yes
  serial: 1
  tasks:
    - name: Create directory for software DVD
      file:
        path: "/software_dvd"
        state: directory

    - name: Install httpd package
      package:
        name: httpd
        state: present

    - name: "Create document root directory"
      file:
        path: /var/www/html
        state: directory
        recurse: yes

    - name: "Remove old index.html file if exists"
      file:
        path: /var/www/html/index.html
        state: absent
      ignore_errors: yes

    - name: "Copy new files"
      copy:
        src: ./index.html
        dest: /var/www/html
        force: no

    - name: "Start the service"
      service:
        name: httpd
        state: started
        enabled: yes

    - name: "Restart the service after copying files"
      service:
        name: httpd
        state: restarted

    - name: "Pause for 10 seconds before proceeding to the next host"
      pause:
        seconds: 20

