---
- name: Execute tasks in parallel on multiple hosts
  hosts: ec2
  gather_facts: no
  tasks:
    - name: Execute task in parallel
      command: uptime
      async: 300
      poll: 0
      register: task_result
      ignore_errors: true  # Handle errors gracefully

    - name: Wait for task to complete
      async_status:
        jid: "{{ task_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 10

    - name: Gather task result
      debug:
        msg: "Task on {{ inventory_hostname }} completed with result: {{ task_result }}"
      when: job_result.finished

    - name: Log playbook execution time
      command: date +"%Y-%m-%d %H:%M:%S"
      register: timestamp_start
      changed_when: false

    # Your additional tasks can be added here for performance monitoring and analysis

    - name: Log playbook completion time
      command: date +"%Y-%m-%d %H:%M:%S"
      register: timestamp_end
      changed_when: false

    - name: Calculate execution time
      debug:
        msg: "Playbook execution time: {{ (timestamp_end.stdout_lines[0] | to_datetime) - (timestamp_start.stdout_lines[0] | to_datetime) }}"

    # Add additional tasks for resource monitoring, error handling, and scalability testing as needed

